name: sensor_msgs
version: "1.0.0"
description: "Sensor message definitions for miniROS - compatible with ROS2 sensor_msgs"
author: "miniROS Team"
license: "MIT OR Apache-2.0"
dependencies: ["std_msgs", "geometry_msgs"]
python_support: true
message_package: true

messages:
  LaserScan:
    description: "Single scan from a planar laser range-finder"
    fields:
      - name: "header"
        type: "std_msgs/Header"
        description: "Header with timestamp and frame info"
      - name: "angle_min"
        type: "float32"
        description: "Start angle of the scan [rad]"
      - name: "angle_max"
        type: "float32"
        description: "End angle of the scan [rad]"
      - name: "angle_increment"
        type: "float32"
        description: "Angular distance between measurements [rad]"
      - name: "time_increment"
        type: "float32"
        description: "Time between measurements [seconds]"
      - name: "scan_time"
        type: "float32"
        description: "Time between scans [seconds]"
      - name: "range_min"
        type: "float32"
        description: "Minimum range value [m]"
      - name: "range_max"
        type: "float32"
        description: "Maximum range value [m]"
      - name: "ranges"
        type: "float32[]"
        description: "Range data [m] (NaN for invalid measurements)"
      - name: "intensities"
        type: "float32[]"
        description: "Intensity data (optional, same length as ranges)"
  
  PointCloud2:
    description: "A collection of 3D points with optional additional information"
    fields:
      - name: "header"
        type: "std_msgs/Header"
        description: "Header with timestamp and frame info"
      - name: "height"
        type: "uint32"
        description: "Height of the point cloud (1 for unordered clouds)"
      - name: "width"
        type: "uint32"
        description: "Width of the point cloud (total number of points for unordered)"
      - name: "fields"
        type: "PointField[]"
        description: "Describes the channels and their layout in the binary data"
      - name: "is_bigendian"
        type: "bool"
        description: "Is this data bigendian?"
      - name: "point_step"
        type: "uint32"
        description: "Length of a point in bytes"
      - name: "row_step"
        type: "uint32"
        description: "Length of a row in bytes"
      - name: "data"
        type: "uint8[]"
        description: "Actual point data, size is (row_step*height)"
      - name: "is_dense"
        type: "bool"
        description: "True if there are no invalid points"
  
  PointField:
    description: "Description of a single field in a PointCloud2"
    fields:
      - name: "name"
        type: "string"
        description: "Name of field"
      - name: "offset"
        type: "uint32"
        description: "Offset from start of point struct"
      - name: "datatype"
        type: "uint8"
        description: "Datatype enumeration"
      - name: "count"
        type: "uint32"
        description: "How many elements in the field"
  
  Imu:
    description: "Inertial Measurement Unit data"
    fields:
      - name: "header"
        type: "std_msgs/Header"
        description: "Header with timestamp and frame info"
      - name: "orientation"
        type: "geometry_msgs/Quaternion"
        description: "Orientation estimate"
      - name: "orientation_covariance"
        type: "float64[9]"
        description: "Row-major representation of orientation covariance matrix"
      - name: "angular_velocity"
        type: "geometry_msgs/Vector3"
        description: "Angular velocity measurement"
      - name: "angular_velocity_covariance"
        type: "float64[9]"
        description: "Row-major representation of angular velocity covariance matrix"
      - name: "linear_acceleration"
        type: "geometry_msgs/Vector3"
        description: "Linear acceleration measurement"
      - name: "linear_acceleration_covariance"
        type: "float64[9]"
        description: "Row-major representation of linear acceleration covariance matrix"
  
  Image:
    description: "Sensor image data"
    fields:
      - name: "header"
        type: "std_msgs/Header"
        description: "Header with timestamp and frame info"
      - name: "height"
        type: "uint32"
        description: "Image height (pixels)"
      - name: "width"
        type: "uint32"
        description: "Image width (pixels)"
      - name: "encoding"
        type: "string"
        description: "Encoding of pixels (mono8, rgb8, bgr8, etc.)"
      - name: "is_bigendian"
        type: "uint8"
        description: "Is data bigendian?"
      - name: "step"
        type: "uint32"
        description: "Full row length in bytes"
      - name: "data"
        type: "uint8[]"
        description: "Actual image data" 