name: Deploy Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/**'

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build documentation
        run: |
          cd docs
          mdbook build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/book

      # Only setup and deploy to Pages on main/develop branches
      - name: Setup Pages
        id: pages
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
        uses: actions/configure-pages@v4
        continue-on-error: true

      - name: Upload Pages artifact
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop') && steps.pages.outcome == 'success'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/book

  # Deploy job - only runs if Pages is properly configured
  deploy:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        continue-on-error: true

      - name: Pages deployment status
        if: steps.deployment.outcome == 'failure'
        run: |
          echo "::warning::GitHub Pages deployment failed. Please ensure:"
          echo "::warning::1. GitHub Pages is enabled in repository settings"
          echo "::warning::2. Source is set to 'GitHub Actions'"
          echo "::warning::3. Repository has proper permissions" 